<?php

    $TERMS_TITLE = "Terms Of services";
    $TERM_DESC = "When your use DiscordTop, you accept this Terms !";

    $TERMS_TAG_1 = "Préambule";
    $TERM_DESC_1 = "Les présentes Conditions Générales d'Utilisation de DiscordTop ont pour objet l'encadrement juridique des modalités de mise à disposition des services du site DISCORDTOP.ORG, de ses services liés (DISCORD-TOP.FR, DTOP.FR et de son Discord), et leur utilisation par « l'Utilisateur ».<br><br> Les conditions générales de DiscordTop doivent être acceptées par tout Utilisateur souhaitant accéder au site. Elles constituent le contrat entre le site et l'Utilisateur.<br><br> L'accès au site par l'Utilisateur signifie que : vous déclarez avoir 13 ans ou plus, si vous êtes majeur dans votre juridiction, vous déclarez avoir lu, compris et accepté d'être lié par les conditions générales de DiscordTop, et si vous avez entre 13 ans et l'âge de la majorité de votre pays, que votre représentant légal a lu, compris et accepté ces présentes conditions générales de DiscordTop.";

    $TERMS_TAG_2 = "Responsable des services";
    $TERM_DESC_2 = "Le Responsable du site est une personne physique, Bryan E., pouvant être contacté par mail : contact[at]bryaan.fr ou par téléphone au 07.56.99.00.64.<br><br>Vous pouvez également nous joindre en ouvrant un ticket sur notre Discord.";

    $TERMS_TAG_3 = "Hébergement des services";
    $TERM_DESC_3 = " Notre fournisseur d'hébergement :  PLANETHOSTER inc., 4416 Louis B. Mayer, Laval (Québec) H7P 0G1, Canada (Site : <a href=\"https://www.planethoster.com/\" target=\"blank\">PlanetHoster</a>)";

    $TERMS_TAG_4 = "Utilisation";
    $TERM_DESC_4 = "DISCORDTOP met à disposition une fonction de publication de serveur discord et un classement de tous les serveurs discord. Nous permettons aux créateurs de serveurs discord d'ajouter leurs serveurs dans notre classement et ainsi donner de la visibilité à ceux-ci. Le classement est disponible sur la page d'accueil du site, les serveurs discords sont triés en fonction de leur nombre de votes, ces votes sont remis à zéro tous les débuts de mois pour permettre aux nouveaux serveurs discord inscrits de prendre place dans le classement.<br><br> Vous acceptez de ne pas, et de ne pas essayer, de copier, d'adapter, d'éditer, de vendre ou d'exploiter DISCORDTOP ou toute partie de DISCORDTOP sans notre autorisation préalable.<br><br> DISCORDTOP se réserve le droit de vous envoyer un avertissement et de suspendre votre compte, si une violation de nos conditions générales d'utilisation ou de notre charte est constatée.";

    $TERMS_TAG_5 = "Votre compte";
    $TERM_DESC_5 = "<strong>Nous ne sommes en aucun cas affiliés à Discord </strong> cependant, nous utilisons le service d'identifiant de Discord pour notre système de connexion/Inscription.<br><br> L'accès à une partie de nos services ne nécessite pas d'avoir un compte, notamment la fonctionnalité de boost. Cependant, pour accéder aux fonctionnalités avancées de DISCORDTOP, il sera nécessaire de créer un compte.<br><br> Vous représentez et vous garantissez que les informations que vous nous fournissez à votre inscription et à tout autre moment sont vraies, précises, actuelles et complètes.<br><br> Nous nous réservons le droit de refuser tout nom d'utilisateur, de suspendre votre compte ou d'empêcher l'utilisation d'un nom d'utilisateur à notre seule discrétion et sans aucune responsabilité envers vous.<br><br> Vous vous assurerez que votre adresse e-mail est correcte et à jour à tout moment. Vous êtes responsable du caractère confidentiel de vos identifiants de connexion et êtes entièrement responsable de toute activité se produisant par l'utilisation de vos identifiants ou de votre Compte.<br><br> Vous acceptez de nous avertir immédiatement si vous pensez que le caractère confidentiel de vos identifiants de connexion a été compromis ou si vous suspectez une utilisation non autorisée de votre Compte.<br><br> Vous acceptez le fait que DISCORDTOP ne sera pas responsable de toute perte ou tout dommage provenant d'une utilisation non autorisée de vos identifiants.";

    $TERMS_TAG_6 = "Les contenus";
    $TERM_DESC_6 = "<strong>Rappel : « En France, la protection par le droit d’auteur est acquise du seul fait de la création de l’oeuvre. »</strong><br><br> L'intégralité du contenu disponible sur le site DISCORDTOP et des services liés sont protégés par le droit d'auteur.<br> La reprise est conditionnée à l'accord de l'auteur en vertu de l' \"Article L.122-4 de la propriété intellectuelle\".<br> Le contenu peut être repris, ou utilisé à des fins associatives, mais la diffusion et/ou l'utilisation de ce contenu à des fins commerciales ou publicitaires est proscrite.<br> Les images diffusées sur le site DISCORDTOP sont des images libres de droits et d'utilisation ou à la propriété de DISCORDTOP.<br> Nous ne sommes pas responsables du contenu des sites sur lesquels nous pouvons vous renvoyer.<br><br><br> Toutes les données que vous mettez en ligne sur DISCORD-TOP et ses services sont de votre responsabilité et doivent respecter notre charte. DISCORDTOP se réserve le droit de supprimer toute donnée qui ne respecterait pas notre charte ou que nous jugerons comme inapropriée, et ce sans pré-avis. Vous pouvez alerter DISCORD-TOP de tout contenu d'utilisateur que vous considérez être en violation avec notre charte ou tout autre comportement d'utilisateur inapproprié en ouvrant un ticket à l'aide de votre espace membre, ou en envoyant un email à contact@anarya.";

    $TERMS_TAG_7 = "La monnaie virtuelle";
    $TERM_DESC_7 = "DISCORDTOP ne fait pas payer les fonctionnalités essentielles à l'utilisation de ses services, mais des « CASH » peuvent être demandés pour l'utilisation de certains services. Les « CASH » représentent la monnaie virtuelle de DISCORDTOP, et ceux-ci sont achetables avec un moyen de paiement légal, avec de l'argent réel.<br><br>Cette monnaie virtuelle n'est pas remboursable, ni échangeable et elle n'est pas non plus cessible dès lors que la monnaie a été créditée.<br><br> DISCORDTOP se réserve le droit de modifier, gérer, contrôler et/ou éliminer de la monnaie virtuelle et/ou des biens virtuels.<br><br> Les tarifs des biens virtuels proposés sont sujets à des changements sans préavis. Pour l'achat de « CASH », nous utilisons un service tiers (Dédipass) pour sécuriser vos paiements, ils mettent à disposition les modes de paiement AudioTel/SmS/NéoSurf/ Carte Bancaire et PayPal.<br><br>En passant votre commande, vous autorisez DISCORDTOP, ou son service de paiement attitré, à facturer le montant de l'achat au compte auquel vous avez recours.";

    $TERMS_TAG_8 = "Les biens virtuels";
    $TERM_DESC_8 = "DISCORDTOP ne garantit pas la disponibilité des biens virtuels mis à disposition.<br><br> Ces biens virtuels sont achetables à l'aide de la monnaie virtuelle et proposent des services différents.<br><br>  DISCORDTOP peut changer les prix de ses biens virtuels à tous moment et ces nouveaux prix seront affichés dans la page d'achat de ces produits.<br><br> Nos abonnements doivent être renouvellé manuellement avant la fin de celeux-ci, si vous ne souhaitez pas le faire, vos abonnements s'arrêteront automatiquement à la fin de leurs durées respectives et l'intégralité des services liés à ces abonnements se désactiveront.<br><br> Certaines données peuvent être enregistrées dans le cas où vous souhaitez racheter un abonnement, tandis que d'autres seront supprimées définitivement.";

    $TERMS_TAG_9 = "Modalités de remboursement";
    $TERM_DESC_9 = " DISCORDTOP offre la possibilité de réclamer un remboursement uniquement dans les cas suivants :<br><u><li>La description du produit acheté ne correspond pas au produit reçu</li><li>Le prix affiché n'est pas le prix que vous avez payé</li></u>Si et seulement si votre demande rentre dans l'un des critères exposés ci-dessus, nous pouvons, éventuellement, proposer un remboursement partiel ou global sous forme de code cadeau uniquement. Aucun remboursement d'argent réel ne sera effectué.";

    $TERMS_TAG_10 = "Indemnisation";
    $TERM_DESC_10 = "Vous acceptez de dédommager et de tenir à couvert DISCORDTOP de toute perte, responsabilité, revendication, requête, dommage, coût et dépense, y compris les frais raisonnables d'avocat découlant de ou en relation avec votre utilisation du et accès au site, votre violation d'une des Conditions, votre violation de tout droit de tierce partie, y compris (mais sans limitation) tout droit d'auteur, propriété ou droit de confidentialité ou accord tiers, ou tout élément de votre contenu ou de vos informations de votre compte ou toute autre information que vous publiez ou partagez sur ou via le Service. Comme utilisé dans cette section, « vous » désigne quiconque accédant à Discord-Top de quelque manière que ce soit.";

    $TERMS_TAG_11 = "Nos revenus";
    $TERM_DESC_11 = " DISCORDTOP vit grâce aux publicités affichées sur notre site, mais également de la vente des biens virtuels.<br><br> L'intégralité des revenus générés grâce à ces sources sont réutilisés pour améliorer et maintenir nos services, et permettre à nos utilisateurs de profiter d'un service stable, de qualité et régulièrement mis à jour.<br><br>L'intégralité des personnes travaillant pour DISCORDTOP sont bénévoles et de ce fait ne sont aucunement rémunérées.";

    $TERMS_TAG_12 = "Confidentialité";
    $TERM_DESC_12 = "Lorsque vous interagissez avec DISCORDTOP, nous pouvons recueillir vos données personnelles. Pour le bon fonctionnement de nos services, nous recueillons votre IP ainsi que les données que vous nous fournissez lors de vos interactions.<br><br>Lorsqu'un membre vote, et qu'il n'est pas inscrit/connecter, pour votre Discord, il dépose un pseudonyme qui permettra aux annonceurs de connaître ses statistiques. Chaque utilisateur accepte de partager ces données en utilisant nos services.<br><br>Il est interdit aux annonceurs de revendre ces données ou de les utiliser à des fins commerciales. Les utilisateurs peuvent demander la non-diffusion de leur(s) pseudo(s) par une simple demande à l'annonceur qui aura l’obligation de respecter cette demande sous peine de suppression de son compte de nos services.";

    $TERMS_TAG_13 = "Newsletter";
    $TERM_DESC_13 = "DISCORDTOP a mis en place un système de newsletter qui nous permet de vous envoyer des emails dans l'objectif de vous annoncer des promotions, ou de vous avertir de certaines nouvelles concernant DISCORDTOP ou votre serveur uniquement.<br>Vous acceptez de base l'envoi de ces e-mails commerciaux mais vous pouvez désactiver ceux-ci via votre espace membre.";

    $TERMS_TAG_14 = "Mises à jour";
    $TERM_DESC_14 = "Nous nous réservons le droit de modifier ces Conditions Générales d'Utilisation de DiscordTop à tout moment et sans préavis.<br><i>Date de parution : 02/05/2020 - Date de la dernière mise à jour";

    $TERMS_TAG_15 = "La charte";
    $TERM_DESC_15 = "Nous avons créé une charte pour permettre d'éclairer nos utilisateurs sur ce qui est autorisé et ce qui est prohibé.</strong><br><a href=\"/guidelines\" style=\"color: #7289DA;\">Consulter la Charte</a>";

?>