<?php

    $GUIDELINES_TITLE = "Regulamin";
    $GUIDELINES_DESC = "Kiedy używasz DiscordTop, akceptujesz ten regulamin !";

    $GUIDELINES_TAG_1 = "Preambuła";
    $GUIDELINES_DESC_1 = "La présente Charte d'Utilisation de DiscordTop a pour objet l'encadrement juridique des modalités d'utilisation des services du site DISCORDTOP.ORG, de ses services liés (DISCORD-TOP.FR, DTOP.FR et de son Discord), et leur utilisation par « l'Utilisateur ».<br><br> La Charte d'Utilisation de DiscordTop doit être acceptée par tout Utilisateur souhaitant accéder au site. Elle constitue le contrat entre le site et l'Utilisateur.<br><br>Toute violation de cette présente Charte d'Utilisation de DiscordTop sera sanctionnée à la hauteur de l'infraction, et il est évident que même si une interdiction n'est pas inscrite ici, cela ne veux pas dire que c'est autorisé, alors faites preuve de bon sens !<br><br>Vous pouvez à tout moment nous suggérer l'ajout d'une règle que vous jugez manquante et importante !";

    $GUIDELINES_TAG_2 = "Rejestracja";
    $GUIDELINES_DESC_2 = "L'inscription n'est pas obligatoire pour l'utilisation simple de DISCORDTOP, elle le devient à partir du moment où un utilisateur souhaite inscrire son serveur discord sur le site, ou bien accéder à des informations sur ses votes.<br><br> Notre système d'inscription et basé sur le système de connexion mis à disposition par Discord.Com. <br><br><strong>DISCORD-TOP est un site indépendant, nous ne sommes pas affiliés à Discord ! Notre équipe ne vous demanderas jamais vos identifiants de connexion, ni de scanner un QRCode !</strong>";

    $GUIDELINES_TAG_3 = "Logowanie";
    $GUIDELINES_DESC_3 = "Vous êtes responsable de votre compte, et vous seul doit pouvoir y avoir accès, ne donnez jamais votre mot de passe à qui que ce soit. <strong>Gardez à l'esprit que notre équipe ne vous demandera jamais l'accès à votre compte !!</strong><br><br>En cas de perte, ou d'oublie, merci de vous référez à votre compte Discord.";

    $GUIDELINES_TAG_4 = "Głosowanie";
    $GUIDELINES_DESC_4 = " Tout utilisateur peut voter pour le serveur de son choix, en respectant le délai entre chaque vote, qui peut-être régulièrement modifié !<br>Pour pouvoir voter, nous demandons l'ajout de votre pseudo, ou la connexion à votre compte Discord, pour que les responsables du serveur discord puisse accéder à des statistiques précises, et éventuellement vous récompenser.<br><br>Depuis le robot, vous pouvez voter, cependant, il faut avoir un compte DiscordTop enregistrer pour que votre vote soit pris en compte !<br><br>Il est important de noter qu'il n'est en aucun cas obligatoire de récompenser les voteurs.<br><br><strong>Toute méthode visant à passer outre le délai prévu est strictement inderdite et se verra lourdement sanctionnée ! De ce fait, l'utilisation de Proxy, VPN, des données mobiles, du WiFi du voisin ou de votre lieu de travail/étude est prohibée.</strong> L'utilisation de ces outils est cependant autorisée si et seulement si vous les utilisez toujours dans le respect du délai prévu entre chaque vote.<br><br>Les pseudonymes lors d'un vote ne doit pas être écrits en caractères spéciaux, et ne doivent pas contenir d'émoticônes.<br><br>DiscordTop n'est pas responsable de vos voteurs, vous êtes responsable de vos votes, de vos membres et vous pouvez très facilement repérer ce type d'infraction, vous avez donc 24 heures pour nous en faire part. Passé ce délai, notre équipe suspendra votre fiche de vote pour une durée variable en fonction de l'importance de l'infraction.<br><br>";

    $GUIDELINES_TAG_5 = "Boosty";
    $GUIDELINES_DESC_5 = "Tout utilisateur peut booster le serveur de son choix, depuis notre robot uniquement.<br>Le délai de vote est de 1 heure par serveur, la vérification est automatique, vous n'êtes pas obligé d'avoir un compte DiscordTop pour pouvoir booster un serveur.<br><br>";

    $GUIDELINES_TAG_6 = "Serwery";
    $GUIDELINES_DESC_6 = "Nous ne sommes en aucun cas responsable de vos serveurs, de son contenu et de son objet. Cependant, nous interdissons certains types de serveurs discord allants à l'encontre de certains principes de nos Conditions Générales, mais également lorsque le contenu et/ou l'objet du serveur est inaproprié. Nous tenons à rappeler que Discord est accessible à des personnes mineures ! De ce fait, les serveurs :<ul><li>Raids ou de harcèlement</li><li>Diffusion d'illustrations ou de contenu pornographique retouché mettant en scène des mineurs (lolicon, shotacon, ou cub)</li><li>Diffusion de contenu portant atteinte à la propriété contractuelle, personnelle, intellectuelle ou à d'autres droits d'une personne</li><li>Diffusion de contenu célébrant ou encourageant, d'une manière générale, l'automutilation ou le suicide. Cela comprend tout contenu encourageant à : se mutiler ou se blesser, adopter l'anorexie, la boulimie ou tout autre trouble du comportement alimentaire, ou à se suicider</li><li>Diffusion d'images d'extrême violence et/ou de cruauté envers les animaux.</li><li>Contenu menaçant de manière directe l'état physique ou financier de quelqu'un.</li><li>Contenu mentent en jeu de l'argent réel (hors organisme déclaré).</li><li>Toute activité illégale (Incluant la promotion et/ou l'encouragement de ces activités, mais ne se limitant pas au piratage, au crack ou à la distribution de logiciels piratés, de codes de triche ou de hacks)</li><li>Partage de contenu suggestif ou violent ayant un rapport avec des mineurs</li><li>Partage de contenu avec l'intention d'embarrasser ou de porter atteinte à la réputation d'un autre individu.</li><li>Diffusion de virus.</li></ul>Notre équipe ne peut pas vérifier tous ses serveurs, cependant, si vous constatez une violation de ces interdictions, contactez-nous dès que possible. Le propriétaire du compte se verra banni de nos services, l'intégralité des données supprimées mais également un courriel sera adressé à Discord Inc pour qu'ils puissent également juger ou punir ces actes.";

    $GUIDELINES_TAG_7 = "Bot";
    $GUIDELINES_DESC_7 = "Le bot mis en place est nullement obligatoire, et il est interdit de faire des requêtes répétitives dans le but de provoquer une surcharge.<br> Nous ne sommes pas responsable de l’ajout de contrefaçon de notre bot, et vous êtes responsables des dégâts que cette contrefaçon pourrait causer.<br> Le bot officiel est certifié par Discord et il est disponible sur cette <a href=\"/me/server\" style=\"color: #7289DA;\">page</a>.";

    $GUIDELINES_TAG_8 = "Pomoc";
    $GUIDELINES_DESC_8 = "Nous avons mis à votre disposition un bon nombre de moyen pour nous contacter rapidement en cas de problème urgent (ne veux pas dire tous vos problèmes), mais également des services avec une réponse plus ou moins rapide en fonction de l'importance. Vous pouvez <a href=\"panel/support\" style=\"color: #7289DA;\">ouvrir un ticket</a>, nous contacter par <a href=\"mailto:contact@discord-top.fr\" style=\"color: #7289DA;\">email</a>, par <a href=\"callto:0756990064\" style=\"color: #7289DA;\">téléphone</a> mais également sur notre <a href=\"https://discord.gg/BQNXqjU\" style=\"color: #7289DA;\">discord</a>.";

?>
